services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./backend/src/:/app/src/
    environment:
      - BACKEND_PORT=5000
      - OLLAMA_BASE_URL=http://ollama-api:11434
